name: PR Comment Test
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
concurrency:
  group: pr-preview-${{ github.event.pull_request.number }}
  cancel-in-progress: false
jobs:
  deploy-preview:
    if: ${{ github.event.action != 'closed' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    defaults:
      run:
        working-directory: packages/server
    steps:
      - uses: actions/checkout@v4
      - &a1
        name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - &a2
        name: Install dependencies
        shell: bash
        run: bun install
      - name: Deploy Preview
        run: bun run testing/github-hello.run.ts --stage pr-${{ github.event.pull_request.number }}
        env:
          GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_PR_AUTHOR: ${{ github.event.pull_request.user }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
